local luaunit = require("luaunit")

TestPartyMembers = require("Comparer\\ComparePartyTest")
TestRaidMembers = require("Comparer\\CompareRaidTest")
TestArenaMembers = require("Comparer\\CompareArenaTest")
TestUnitGetUnits = require("Unit\\GetUnitsTest")
TestNormaliseUnits = require("Unit\\Normalise")
TestUnitMacro = require("Macro\\ParserTest")
TestUnitOptionsUpgrader = require("Configuration\\UpgradeOptionsTest")
TestUnitEnumerable = require("Collections\\EnumerableTest")
TestLuaEx = require("Language\\LuaExTest")

TestApiV1 = require("Api\\ApiV1")
TestApiV2 = require("Api\\ApiV2")
TestApiV3 = require("Api\\ApiV3")
TestMacro = require("Modules\\Macro")
TestHidePlayer = require("Modules\\HidePlayer")
TestTargeting = require("Modules\\Targeting")
TestSorting = require("Modules\\Sorting")
TestSpacing = require("Modules\\Spacing")
TestAddon = require("Modules\\Addon")

TestFrameChain = require("Frame\\FrameChain")

os.exit(luaunit:run())
