local luaunit = require("luaunit")

TestPartyMembers = require("Comparer\\ComparePartyTest")
TestRaidMembers = require("Comparer\\CompareRaidTest")
TestArenaMembers = require("Comparer\\CompareArenaTest")
TestUnitGetUnits = require("Unit\\GetUnitsTest")
TestUnitMacro = require("Macro\\ParserTest")
TestUnitOptionsUpgrader = require("Configuration\\UpgradeOptionsTest")
TestUnitEnumerable = require("Collections\\EnumerableTest")
TestLuaEx = require("Language\\LuaExTest")

TestComponentTestApiV1 = require("Api\\ApiV1")
TestComponentTestApiV2 = require("Api\\ApiV2")
TestComponentTestMacro = require("Modules\\Macro")
TestComponentTestHidePlayer = require("Modules\\HidePlayer")
TestComponentTestTargeting = require("Modules\\Targeting")
TestComponentTestSorting = require("Modules\\Sorting")
TestComponentTestSpacing = require("Modules\\Spacing")
TestComponentTestAddon = require("Modules\\Addon")

os.exit(luaunit:run())
