---@meta
---@class HealthCheckResult
---@field Passed boolean true if passed, otherwise false.
---@field Description string description of the health check.
---@field Help string further details regarding the issue.
