---@meta
---@class HealthCheckResult
---@field Passed boolean true if passed, otherwise false.
---@field Applicable boolean true if this health check result is applicable to the current environment.
---@field Description string description of the health check.
---@field Help string further details regarding the issue.
