---@meta
---@class OptionsBuilder
---@field HorizontalSpacing number
---@field VerticalSpacing number
---@field TextShim fun(self: table, frame: table)
---@field Sorting OptionsPanel
---@field Spacing OptionsPanel
---@field Health OptionsPanel
---@field Keybinding OptionsPanel
---@field SortingMethod OptionsPanel
---@field Macro OptionsPanel
---@field Integration OptionsPanel
