---@meta
---@alias Area
---| "Arena"
---| "Arena - 2v2"
---| "Arena - Default"
---| "Dungeon"
---| "Raid"
---| "World"

---@class SpacingArea
---@field Horizontal number
---@field Vertical number
