---@meta
---@class Configuration
---@field Init fun(self: table)
---@field Panels Panels
---@field HorizontalSpacing number
---@field VerticalSpacing number
---@field Defaults Options
---@field PlayerSortMode PlayerSortModeEnum
---@field GroupSortMode GroupSortModeEnum
---@field SortingMethod SortingMethodEnum
---@field Upgrader OptionsUpgrader
---@field RegisterConfigurationChangedCallback fun(self: table, callback: fun())
---@field NotifyChanged fun(self: table)
---@field TextLine fun(self: table, line: string, parent: table, anchor: table?, font: string?, verticalSpacing: number?): table anchor
---@field TextBlock fun(self: table, lines: string[], parent: table, anchor: table): table anchor
---@field MultilineTextBlock fun(self: table, lines: string, parent: table, anchor: table): table anchor
---@field Dropdown fun(self: table, parent: table, items: table, getValue: (fun(): any), setValue: (fun(value: any)), getText?: (fun(value: any): string)): table
---@field Specs Specs
---@field DiscordUrl string
---@field SettingsSize fun(self: table): width: number, height: number

---@class Panels
---@field Sorting OptionsPanel
---@field Spacing OptionsPanel
---@field Health OptionsPanel
---@field Keybinding OptionsPanel
---@field Macro OptionsPanel
---@field MacroVariables OptionsPanel
---@field Addons OptionsPanel
---@field SpecOrdering OptionsPanel
---@field SpecPriority OptionsPanel
---@field AutoLeader OptionsPanel
---@field SortingMethod OptionsPanel
---@field Api OptionsPanel
---@field Discord OptionsPanel
---@field Log OptionsPanel
