---@meta
---@class FrameProvider: IProcessEvents
---@field Name fun(self: table): string Returns the display name for this provider.
---@field Init fun(self: table) Performs any initialisation logic the provider might have.
---@field Enabled fun(self: table): boolean Whether the provider is enabled.
---@field RegisterRequestSortCallback fun(self: table, callback: fun(provider: FrameProvider)) Registers a callback to be invoked when sorting is required.
---@field RegisterContainersChangedCallback fun(self: table, callback: fun(provider: FrameProvider)) Registers a callback to be invoked when container metadata may have changed.
---@field Containers fun(self: table): FrameContainer[]

---@class Providers: IInitialise
---@field Blizzard BlizzardFrameProvider
---@field sArena FrameProvider
---@field GladiusEx FrameProvider
---@field ElvUI FrameProvider
---@field Cell FrameProvider
---@field All FrameProvider[]
---@field Enabled fun(self: table): FrameProvider[]
